// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPXNPiTV6Sm3cTMdIrhTxOAdWRjkJdv_I',
    appId: '1:1000858105446:web:627d7fbf34bc8c2d291fa7',
    messagingSenderId: '1000858105446',
    projectId: 'tuncdating',
    authDomain: 'tuncdating.firebaseapp.com',
    storageBucket: 'tuncdating.appspot.com',
    measurementId: 'G-EEQMS7DFN7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlhuYfq7TpLMpAdQNFw3tAFSPnl-Y4nVQ',
    appId: '1:1000858105446:android:2cfd4490e8d1a028291fa7',
    messagingSenderId: '1000858105446',
    projectId: 'tuncdating',
    storageBucket: 'tuncdating.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQzn7GpaQnrgSsQm8YIycmckww_A8ZcFI',
    appId: '1:1000858105446:ios:dd4339274e30dd50291fa7',
    messagingSenderId: '1000858105446',
    projectId: 'tuncdating',
    storageBucket: 'tuncdating.appspot.com',
    iosClientId: '1000858105446-sjmsod6vomoh3a9dq8vv6os6rq0lnheo.apps.googleusercontent.com',
    iosBundleId: 'site.tunckankilic.tuncdating',
  );
}
