export 'auth/screens/login_screen.dart';
export 'auth/screens/register_screen.dart';
export 'splash/splash_screen.dart';
export 'main/home_screen.dart';
export 'main/fsfr.dart';
export 'main/lslr.dart';
export 'main/swipe_screen.dart';
export 'main/vsvr.dart';
export "main/user_details.dart";
